# 5 EJERCICIOS DE PREPROCESAMIENTO

```
Docente: CARLOS FERNANDO MONTOYA CUBAS
Alumno: MANUEL HUMBERTO VELARDE FLORES
```

## Acceso al entorno spark

In [1]:
import findspark
findspark.init()
 
import pyspark
from pyspark.sql import SparkSession
from pyspark import SparkContext
spark = SparkSession.builder.getOrCreate()
sc = SparkContext.getOrCreate()

1. SIMILITUD DE COSENOS

In [2]:
def cosenos(x,y):
    """
    Calcula la distancia de cosenos

    Args:
        x (double): Un número de tipo double
        y (double): Un número de tipo double

    Returns:
        double: Un número de tipo double equivalente a la distancia de coseno de x e y
    """
    return ((x*y)/((x*x)*(y*y)))
print(cosenos(3,4))

0.08333333333333333


In [5]:
listaNumeros = [(1,2), (5,10), (20,3), (3,4)]
numerosRDD = sc.parallelize(listaNumeros, 4)
print(numerosRDD.collect())

[(1, 2), (5, 10), (20, 3), (3, 4)]


In [6]:
variosRDD = numerosRDD.map(lambda x: cosenos(x[0],x[1]))
print (variosRDD.collect())

[0.5, 0.02, 0.016666666666666666, 0.08333333333333333]


2. Escalonamiento

In [7]:
def maxminScale(x):
    """
    Realiza escalonamiento para un arreglo numérico

    Args:
        x (array of doubles): Un arreglo de números de tipo double

    Returns:
        RDD of doubles: RDD de números de tipo double con los valores escalonados
    """
    minX = min(x)
    maxX = max(x)
    xRDD = sc.parallelize(x, 5)
    maxminArray = xRDD.map(lambda x: (x-minX)/(maxX-minX))
    return maxminArray

In [8]:
arraySinEscalonar = [10,20,3,4,14,132,2]
print(arraySinEscalonar)

[10, 20, 3, 4, 14, 132, 2]


In [9]:
arrayEscalonadoRDD = maxminScale(arraySinEscalonar)
print (arrayEscalonadoRDD.collect())

[0.06153846153846154, 0.13846153846153847, 0.007692307692307693, 0.015384615384615385, 0.09230769230769231, 1.0, 0.0]


3. Normalización

In [13]:
import math
def norm(x):
    """
    Realiza la normalización para los elementos de un arreglo
    
    Args:
        x (numeric array): Un arreglo de números
        
    Returns:
        RDD of doubles: RDD de números de tipo double con los valores normalizados
    """
    xRDD = sc.parallelize(x, 5)
    cuadrados = xRDD.map(lambda x: x*x)
    total = cuadrados.sum()
    raiz = math.sqrt(total)
    rddNorm = xRDD.map(lambda x: (x/raiz))
    return rddNorm

In [25]:
arraySinNormalizar = [10,20,3,4,14,132,2]
print(arraySinNormalizar)

[10, 20, 3, 4, 14, 132, 2]


In [26]:
arrayNormalizadoRDD = norm(arraySinNormalizar)
print(arrayNormalizadoRDD.collect())

[0.07422900680690823, 0.14845801361381647, 0.022268702042072472, 0.029691602722763295, 0.10392060952967153, 0.9798228898511887, 0.014845801361381647]


4. Estandarización

In [16]:
def estandarizacion(x):
    """
    Estandariza los elementos de un arreglo
    
    Args:
        x (numeric array): Un arreglo de números
        
    Returns:
        RDD of doubles: RDD de números de tipo double con los valores estandarizados
    """
    xRDD = sc.parallelize(x, 5)
    media = xRDD.mean()
    desv = xRDD.stdev()
    rddEst = xRDD.map(lambda x : (x-media)/desv)
    return rddEst

In [27]:
arraySinEstandarizar = [10,20,3,4,14,132,2]
print(arraySinEstandarizar)

[10, 20, 3, 4, 14, 132, 2]


In [28]:
arrayEstandarizadoRDD = estandarizacion(arraySinEstandarizar)
print(arrayEstandarizadoRDD.collect())

[-0.37746938822413884, -0.14770541278335866, -0.538304171032685, -0.5153277734886069, -0.2855637980478268, 2.4256511121533793, -0.561280568576763]


5. Minkowski

In [32]:
import math
def minkowski(xRDD, p):
    """
    Devuelve la distancia de Minkowski de dos vectores numéricos.

    Args:
        xRDD (RDD of doubles): RDD de dos vectores de numeros.
        p (int): Número entero que representa el exponente interno y el índice radical

    Returns:
        double: Distancia entre dos vectores numéricos.
    """
    sumatoria = xRDD.map(lambda x: math.pow(abs(x[0]-x[1]),2)).sum()
    resMinkowski = math.pow(sumatoria,1/p)
    return(resMinkowski)

In [33]:
import numpy as np
# Usaremos vectores aleatorios
xRDD = sc.parallelize(np.random.random(size=(10,2)),3)
xRDD.collect()

[array([0.37300923, 0.69433584]),
 array([0.91416461, 0.69123269]),
 array([0.55350973, 0.82490504]),
 array([0.09287674, 0.50935804]),
 array([0.78988058, 0.65208356]),
 array([0.67574367, 0.52491406]),
 array([0.724133  , 0.13582152]),
 array([0.6030266 , 0.16315708]),
 array([0.04763802, 0.46890279]),
 array([0.84583735, 0.11825824])]

In [35]:
distanciaMinkowski = minkowski(xRDD,4)
print(distanciaMinkowski)

1.1398767795285785
